version: '3.8'

services:
    tests:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/code
        working_dir: /code
        depends_on:
            - mongodb
        command: tail -f /dev/null

    mongodb:
        container_name: mongodb_
        image: mongo:7.0
        ports:
            - "27017:27017"
